# Generated by Django 6.0.3 on 2026-04-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_user_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_organizer',
        ),
    ]
