# Generated by Django 6.0.3 on 2026-04-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_rename_is_admin_user_is_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_site_admin',
            field=models.BooleanField(default=False),
        ),
    ]
