# Generated by Django 6.0.3 on 2026-04-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_user_is_site_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='bgg_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='bgg_last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='bgg_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
