# Generated by Django 6.0.3 on 2026-04-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_boardgame_bgg_id_boardgame_bgg_last_synced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=63),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone_detected',
            field=models.BooleanField(default=False),
        ),
    ]
