# Generated by Django 6.0.3 on 2026-04-16 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_user_timezone_user_timezone_detected'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='voting_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='voting_open',
            field=models.BooleanField(default=True),
        ),
    ]
