# Generated by Django 6.0.3 on 2026-04-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_event_voting_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='bgg_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='complexity',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('medium', 'Medium'), ('medium_heavy', 'Medium Heavy'), ('heavy', 'Heavy'), ('unknown', 'Unknown')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='voting_deadline',
            field=models.DateTimeField(),
        ),
    ]
