# Generated by Django 6.0.3 on 2026-04-17 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_add_complexity_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username must contain only letters, numbers, underscores, periods, and dashes.', regex='^[a-zA-Z0-9_.-]+\\Z')]),
        ),
    ]
