# Generated by Django 6.0.3 on 2026-04-18 02:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='verified_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be at least 4 characters and contain only letters, numbers, underscores, periods, and dashes. It must start with a letter and end with a letter or number.', regex='^[a-zA-Z][a-zA-Z0-9_.\\-]{2,}[a-zA-Z0-9]\\Z')]),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.verifiedicon'),
        ),
    ]
