# Generated by Django 6.0.3 on 2026-04-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_date_joined',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_events',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_games',
            field=models.BooleanField(default=True),
        ),
    ]
