# Generated by Django 6.0.3 on 2026-04-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_add_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_voting_offset_minutes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='voting_deadline_offset_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
