# Generated by Django 6.0.3 on 2026-04-23 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0015_add_site_settings_and_event_offset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='group_images/')),
                ('discoverable', models.BooleanField(default=True)),
                ('join_policy', models.CharField(choices=[('open', 'Open'), ('request', 'Request Approval'), ('invite_only', 'Invite Only')], default='open', max_length=20)),
                ('max_members', models.PositiveIntegerField(default=50)),
                ('disbanded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
