# Generated by Django 6.0.3 on 2026-04-23 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0017_add_group_membership_invite_joinrequest_creationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.group'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_site_admins_to_delete_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='group_creation_override',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
