# Generated by Django 6.0.3 on 2026-04-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0020_event_group_non_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_organizer',
        ),
    ]
