# Generated by Django 6.0.3 on 2026-04-25 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0021_remove_is_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_games', to='club.group'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
