# Generated by Django 6.0.3 on 2026-04-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0022_boardgame_group_alter_boardgame_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_view_only',
            field=models.BooleanField(default=False),
        ),
    ]
