# Generated by Django 6.0.3 on 2026-04-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0025_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='decline_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='friendship',
            name='last_declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
