# Generated by Django 6.0.3 on 2026-04-27 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0026_friendship_decline_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_organizers',
            field=models.ManyToManyField(blank=True, related_name='co_organized_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_invite_others',
            field=models.CharField(choices=[('nobody', 'Nobody'), ('friends_only', 'Friends Only'), ('anyone', 'Anyone')], default='nobody', max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='auto_add_games',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='organizers_can_edit_datetime',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organizers_can_edit_description',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organizers_can_edit_title',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='privacy',
            field=models.CharField(choices=[('private', 'Private'), ('invite_only_public', 'Invite Only - Public'), ('public', 'Public')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='show_attendees_publicly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='show_datetime_publicly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='show_description_publicly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='show_location_publicly',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.group'),
        ),
        migrations.CreateModel(
            name='PrivateEventCreationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='club.event')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='unique_event_invite')],
            },
        ),
    ]
