# Generated by Django 6.0.3 on 2026-04-29 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0030_event_presence'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGameOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('board_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.boardgame')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.event')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'board_game'), name='unique_event_game_override')],
            },
        ),
    ]
