# Generated by Django 6.0.3 on 2026-05-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0032_game_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
