# Generated by Django 6.0.3 on 2026-05-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0036_seed_default_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_in_search',
            field=models.BooleanField(default=True),
        ),
    ]
