# Generated by Django 6.0.3 on 2026-05-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0037_add_show_in_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_lockdown_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_lockdown_allow_site_admins',
            field=models.BooleanField(default=False),
        ),
    ]
