# Generated by Django 6.0.3 on 2026-05-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0039_add_event_duration_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedicon',
            name='image',
            field=models.ImageField(upload_to='verified_icons/'),
        ),
    ]
