# Generated by Django 6.0.3 on 2026-05-28 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0040_alter_verifiedicon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='co_creators',
            field=models.ManyToManyField(blank=True, related_name='co_created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_co_creators',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
