# Generated by Django 6.0.3 on 2026-05-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0041_add_co_creators_and_max_co_creators_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_friends',
            field=models.BooleanField(default=False),
        ),
    ]
