# Generated by Django 6.0.3 on 2026-05-29 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0042_add_show_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='auto_add_games',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GameOwnershipProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('board_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_proposals', to='club.boardgame')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_proposals', to='club.event')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_game_proposals', to=settings.AUTH_USER_MODEL)),
                ('proposed_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_game_proposals', to='club.group')),
                ('proposed_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_game_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('board_game',), name='unique_pending_proposal_per_game')],
            },
        ),
    ]
