from django.contrib.auth import views as auth_views
from django.urls import path

from club import views
from club.forms import EmailOrUsernameLoginForm

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('beta-access/', views.beta_access, name='beta_access'),
    path('settings/', views.user_settings, name='user_settings'),
    path('settings/add-icon/', views.add_verified_icon, name='add_verified_icon'),
    path('settings/delete-icon/<int:pk>/', views.delete_verified_icon, name='delete_verified_icon'),
    path('save-timezone/', views.save_timezone, name='save_timezone'),
    path('register/', views.register, name='register'),
    path('login/', views.CustomLoginView.as_view(template_name='registration/login.html', authentication_form=EmailOrUsernameLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('change-password/', views.forced_password_change, name='forced_password_change'),
    path('verify-email/<str:token>/', views.verify_email, name='verify_email'),
    path('set-password/<str:token>/', views.user_set_password, name='user_set_password'),
    path('groups/', views.group_list, name='group_list'),
    path('groups/create/', views.group_create, name='group_create'),
    path('groups/<slug:slug>/', views.group_dashboard, name='group_dashboard'),
    path('groups/<slug:slug>/settings/', views.group_settings, name='group_settings'),
    path('groups/<slug:slug>/favorite/', views.group_favorite, name='group_favorite'),
    path('groups/<slug:slug>/delete/', views.group_delete, name='group_delete'),
    path('groups/<slug:slug>/restore/', views.group_restore, name='group_restore'),
    path('groups/<slug:slug>/members/', views.group_members, name='group_members'),
    path('groups/<slug:slug>/members/manage/', views.group_members_manage, name='group_members_manage'),
    path('groups/<slug:slug>/join/', views.group_join, name='group_join'),
    path('groups/<slug:slug>/leave/', views.group_leave, name='group_leave'),
    path('groups/<slug:slug>/join-requests/', views.group_join_request_manage, name='group_join_request_manage'),
    path('groups/<slug:slug>/games/', views.group_games, name='group_games'),
    path('groups/<slug:slug>/games/add/', views.group_game_add, name='group_game_add'),
    path('groups/<slug:slug>/invite/', views.group_invite_create, name='group_invite_create'),
    path('invite/<str:token>/', views.group_invite_accept, name='group_invite_accept'),
    path('games/', views.game_list, name='game_list'),
    path('games/add/', views.game_add, name='game_add'),
    path('games/bgg-search/', views.bgg_search, name='bgg_search'),
    path('games/bgg-import/<int:bgg_id>/', views.bgg_import, name='bgg_import'),
    path('games/<int:pk>/', views.game_detail, name='game_detail'),
    path('games/<int:pk>/edit/', views.game_edit, name='game_edit'),
    path('games/<int:pk>/delete/', views.game_delete, name='game_delete'),
    path('events/', views.event_list, name='event_list'),
    path('groups/<slug:slug>/events/', views.group_event_list, name='group_event_list'),
    path('groups/<slug:slug>/events/add/', views.event_add, name='event_add'),
    path('groups/<slug:slug>/events/add/recurring/', views.event_add_recurring, name='event_add_recurring'),
    path('groups/<slug:slug>/events/add/recurring/preview/', views.event_add_recurring_preview, name='event_add_recurring_preview'),
    path('groups/<slug:slug>/events/<int:pk>/edit/', views.event_edit, name='event_edit'),
    path('groups/<slug:slug>/events/<int:pk>/', views.event_detail, name='event_detail'),
    path('groups/<slug:slug>/events/<int:pk>/rsvp/', views.event_rsvp, name='event_rsvp'),
    path('groups/<slug:slug>/events/<int:pk>/vote/', views.event_vote, name='event_vote'),
    path('groups/<slug:slug>/events/<int:pk>/results/', views.event_results, name='event_results'),
    path('groups/<slug:slug>/events/<int:pk>/toggle-visibility/', views.event_toggle_visibility, name='event_toggle_visibility'),
    path('groups/<slug:slug>/events/<int:pk>/toggle-voting/', views.event_toggle_voting, name='event_toggle_voting'),
    path('manage-users/', views.manage_users, name='manage_users'),
    path('manage-users/confirm/', views.manage_users_confirm, name='manage_users_confirm'),
    path('manage-users/cancel/', views.manage_users_cancel, name='manage_users_cancel'),
    path('manage-users/add/', views.user_add, name='user_add'),
    path('manage-users/<int:pk>/delete/', views.user_delete, name='user_delete'),
    path('notifications/', views.notification_list, name='notification_list'),
    path('notifications/<int:pk>/read/', views.notification_mark_read, name='notification_mark_read'),
    path('notifications/read-all/', views.notification_mark_all_read, name='notification_mark_all_read'),
    path('notifications/delete-selected/', views.notification_delete_selected, name='notification_delete_selected'),
    path('profile/<str:username>/', views.public_profile, name='public_profile'),
]
